name: Run Berghain Script (10x every 15 min)

#on:
#  schedule:
#    - cron: "*/15 * * * *"
#  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input: [1,1,2,2,2,2,3,3,3,3]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python main.py ${{ matrix.input }}
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

